services:
  nest-app:
    build: .
    container_name: nest-app
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
